# Generated by Django 4.1.2 on 2022-11-21 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_type', models.CharField(choices=[('V', 'Vlog'), ('B', 'Blog')], max_length=20)),
                ('content', models.TextField(blank=True, null=True)),
                ('external_link', models.URLField(blank=True, null=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
