# Generated by Django 4.1.2 on 2022-11-21 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default='Example', max_length=100),
            preserve_default=False,
        ),
    ]
