"""
Django settings for eco_marketplace project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# env = environ.Env(
#     # set casting, default value
#     DEBUG=(bool, False)
# )

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

STRIPE_PK_TEST = 'pk_test_51M6z9KDGwObfk40iF1zi8zMoa8PKevdBc7G55H6A2WmwPseQm8C72Dja5xL2rkoz0FJxf2vIC3SgEvmvNSBmy58P00YLtALJWA'
STRIPE_SK_TEST = 'sk_test_51M6z9KDGwObfk40ipcK9NsTjbCQoD8RNWxkS6xbcvRIq0E5RRPR1wIFTPB1osKyNBWKniHOWoZUlaOG9eHMU6Lus00Kgis60b6'
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '"z+a!oqez6-ie6vtzjh+6*@3w)e6#y$c_ef%n1+ypjnjtety@)c"'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [ 
    'localhost',
    'web-production-8fd9.up.railway.app',
    'https://gorgeous-sawine-faaa7b.netlify.app',
    'https://carbon-platform-v1.herokuapp.com',
    'carbon-platform-v1.herokuapp.com',
    'https://web-production-8fd9.up.railway.app',
    '127.0.0.1'
]


# CORS


CORS_ORIGIN_WHITELIST = [
    'http://localhost:8080',
    'https://gorgeous-sawine-faaa7b.netlify.app',
    'https://carbon-platform-v1.herokuapp.com',
    'https://web-production-8fd9.up.railway.app',
]

ALGOLIA_APP_ID =  'B8LL3M4JX0'

ALGOLIA_API_KEY = '929f8e8903443063ba331a6bcfadc897'

ALGOLIA = {
    'APPLICATION_ID': 'B8LL3M4JX0',
    'API_KEY': 'd4efaae7309f0667b068b5162a2660bb'
}


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # third-party
    'rest_framework',
    'storages',
    'corsheaders',
    'algoliasearch_django',

    # internal,
    'products',
    'users',
    'vendors',
    'reviews',
    'categories',
    'tags',
    'blogs'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'eco_marketplace.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'eco_marketplace.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'railway',
        'USER': 'postgres',
        'PASSWORD': "M3mWih1GzdwAeHfaYdK6",
        'HOST': 'containers-us-west-133.railway.app',
        'PORT': '7325'
    }
}

# postgresql://postgres:M3mWih1GzdwAeHfaYdK6@containers-us-west-133.railway.app:7325/railway




# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'


""
#S3 BUCKETS CONFIG

# AWS_ACCESS_KEY_ID = env("AWS_ACCESS_KEY_ID")
# AWS_SECRET_ACCESS_KEY = env("AWS_SECRET_ACCESS_KEY")
# AWS_STORAGE_BUCKET_NAME = env("AWS_STORAGE_BUCKET_NAME")

AWS_QUERYSTRING_AUTH = False


# AWS_S3_FILE_OVERWRITE = env("AWS_S3_FILE_OVERWRITE")
# AWS_DEFAULT_ACL = env("AWS_DEFAULT_ACL")
# DEFAULT_FILE_STORAGE = env("DEFAULT_FILE_STORAGE")

# STATICFILES_STORAGE = env("STATICFILES_STORAGE")

# STATIC_URL = '/static/'
# STATIC_ROOT = BASE_DIR / 'static'

if DEBUG:
    CLIENT_URL = "https://gorgeous-sawine-faaa7b.netlify.app" #"http://localhost:8080"
else:
    CLIENT_URL = "https://gorgeous-sawine-faaa7b.netlify.app"