# Generated by Django 4.1.2 on 2022-11-09 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('icon', models.URLField()),
                ('image', models.URLField()),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
    ]
