# Generated by Django 4.1.2 on 2022-11-09 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
