# Generated by Django 4.1.2 on 2022-11-10 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_alter_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='bg_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='promotional_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
