# Generated by Django 4.1.2 on 2022-11-10 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_category_bg_color_category_promotional_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='icon',
            new_name='icon_url',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='image_url',
        ),
    ]
