# Generated by Django 4.1.2 on 2022-11-07 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='logo',
            field=models.URLField(default=None, null=True),
        ),
    ]
