# Generated by Django 4.1.2 on 2022-11-11 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_alter_review_product_alter_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='logo',
        ),
    ]
