# Generated by Django 4.1.2 on 2022-11-06 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0002_remove_vendor_id_alter_vendor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('active_discount', models.DecimalField(decimal_places=2, default=0, max_digits=2, null=True)),
                ('variant_SKU', models.CharField(max_length=40)),
                ('carbon_footprint', models.DecimalField(decimal_places=3, max_digits=6)),
                ('product_category', models.CharField(max_length=40)),
                ('tags', models.CharField(max_length=512)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='vendors.vendor')),
            ],
        ),
    ]
