# Generated by Django 4.1.2 on 2022-11-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='SEO_description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='SEO_title',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='cost_per_item',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='gift_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='google_shopping_MPN',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='google_shopping_adWords_grouping',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='google_shopping_adWords_labels',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='google_shopping_age_group',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='google_shopping_condition',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='google_shopping_custom_label0',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='google_shopping_custom_label1',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='google_shopping_custom_label2',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='google_shopping_custom_label3',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='google_shopping_custom_label4',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='google_shopping_custom_product',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='google_shopping_gender',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='google_shopping_google_product_category',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_alt_text',
            field=models.TextField(default='No alt text found'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_position',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_src',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='option1_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='option1_value',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='option2_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='option2_value',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='option3_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='option3_value',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_barcode',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_compare_at_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_fulfillment_policy',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_grams',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_inventory_policy',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_inventory_quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='variant_inventory_tracker',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_requires_shipping',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_tax_code',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_taxable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_weight_unit',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
