# Generated by Django 4.1.2 on 2022-11-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_seo_description_product_seo_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AlterField(
            model_name='product',
            name='body',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
