# Generated by Django 4.1.2 on 2022-11-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_price_alter_product_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='active_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
    ]
