# Generated by Django 4.1.2 on 2022-11-07 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_active_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='vendor',
            new_name='vendor_name',
        ),
    ]
