# Generated by Django 4.1.2 on 2022-11-07 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_remove_vendor_id_alter_vendor_name'),
        ('products', '0006_rename_vendor_product_vendor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor_name',
            field=models.ForeignKey(blank=True, db_column='vendor_name', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='vendors.vendor'),
        ),
    ]
