# Generated by Django 4.1.2 on 2022-11-07 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_vendor_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='vendor_name',
            new_name='vendor',
        ),
    ]
