# Generated by Django 4.1.2 on 2022-11-07 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_rename_vendor_name_product_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='variant_fulfillment_policy',
            new_name='variant_fulfillment_service',
        ),
    ]
