# Generated by Django 4.1.2 on 2022-11-07 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_rename_variant_fulfillment_policy_product_variant_fulfillment_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='variant_inventory_quantity',
            new_name='variant_inventory_qty',
        ),
    ]
