# Generated by Django 4.1.2 on 2022-11-07 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_rename_variant_inventory_quantity_product_variant_inventory_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='variant_SKU',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
