# Generated by Django 4.1.2 on 2022-11-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_product_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_alt_text',
            field=models.TextField(default='No alt text found', null=True),
        ),
    ]
