# Generated by Django 4.1.2 on 2022-11-08 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_remove_vendor_id_alter_vendor_name'),
        ('products', '0017_alter_product_image_alt_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(blank=True, db_column='vendor_name', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='vendors.vendor'),
        ),
    ]
