# Generated by Django 4.1.2 on 2022-11-08 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_product_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='variant_inventory_qty',
            field=models.IntegerField(null=True),
        ),
    ]
