# Generated by Django 4.1.2 on 2022-11-08 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_product_variant_inventory_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='variant_requires_shipping',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='variant_taxable',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
