# Generated by Django 4.1.2 on 2022-11-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_remove_product_product_category_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
