# Generated by Django 4.1.2 on 2023-01-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_alter_product_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='handle',
            field=models.CharField(max_length=200),
        ),
    ]
