# Generated by Django 4.1.2 on 2023-01-03 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_alter_product_option1_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='option2_name',
        ),
        migrations.AlterField(
            model_name='product',
            name='option1_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='option1_value',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='option2_value',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='option3_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='option3_value',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
