# Generated by Django 4.1.2 on 2023-01-03 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_remove_product_option2_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='option2_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
