# Generated by Django 4.1.2 on 2023-01-04 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_product_option2_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='active_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2, null=True),
        ),
    ]
