# Generated by Django 4.1.2 on 2023-01-04 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_alter_product_active_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='carbon_footprint',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
    ]
