# Generated by Django 4.1.2 on 2023-01-18 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_product_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vendor',
        ),
        migrations.AddField(
            model_name='product',
            name='vendor_name',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
