# Generated by Django 4.1.2 on 2023-01-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_remove_product_vendor_product_vendor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='handle',
            field=models.CharField(max_length=500),
        ),
    ]
