# Generated by Django 4.1.2 on 2023-01-20 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_alter_product_image_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='variant_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
