# Generated by Django 4.1.2 on 2023-01-21 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0042_alter_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='variant_SKU',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
